version: '3.8'

services:
  bot:
    build: .
    container_name: summary_bot
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_URL=redis://redis:6379/0
      - SUMMARY_INTERVAL_MINUTES=${SUMMARY_INTERVAL_MINUTES:-60}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    container_name: summary_bot_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always

volumes:
  redis_data:
